export const CHANGE_INPUT_VALUE = 'changeInputValue'
export const ADD_TODO_ITEM = 'addTodoItem'
export const DELETE_TODO_ITEM = 'deleteTodoItem'
export const INIT_LIST_ACTION = 'initListAction'
export const GET_INIT_LIST = 'get_Init_List'